### ISSUE TITLE
Github build cache

### ISSUE THREAD

**Issue by Napolitain** [Napolitain/opengl-solar-system#9]
**Describe the bug**
Since the build is extremely long, github action should use perfectly github's cache for faster builds.

**To Reproduce**

- cmake run

**Expected behavior**
Fast incremental builds

**Screenshots**

**Desktop (please complete the following information):**
- Github runner

**Comment by lab34** [comment]
currently trying to implement this: https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/
